<?php 
	$title = 'Terms of Service Crypto Soul';
	include('../header.php');
?>
	<p class="h">Terms of Service Crypto Soul</p>
<p>Последнее обновление: 16 октября 2021 года</p>
<p>Русский: Условия предоставлены только на Английском языке. Пожалуйста, воспользуйтесь услугами переводчика или специальными программами для того, чтобы воспользоваться условиями сервиса, если вы не понимаете их.</p>
<p>Español: Los términos se proporcionan solo en inglés. Utilice los servicios de un intérprete o programas especiales para utilizar los términos de servicio si no los comprende.</p>
<p>简体中文: 条款仅以英文提供。 如果您不理解服务条款，请使用口译或特殊程序的服务以使用服务条款。</p>
<p>_______________________________________________________________________________________</p>
<p>The Crypto Soul Terms of Service are concluded between you, as an individual who has reached the age of 18 (hereinafter referred to as “you” / “your” or other names of a second person) and CRYPTO SOUL LIMITED (hereinafter referred to as “Crypto Soul” / “us” / “our” / “we” / “Service”). If you register in this Service, use any of the Services provided in this Service, click on “Completely agree” button, you agree that you have read, understood, and accepted all the conditions specified in these Terms of Service — (hereinafter referred to as “Terms”), as well as with all Regulatory instruments presented in the Service and Privacy Policy. In addition, when using certain features of the Service, you may be subject to certain additional terms that apply to those features.</p>
<p>Please pay attention to the following:</p>
<p>1.	Crypto Soul does not release digital assets that you use on this Service;</p>
<p>2.	You assume all risks associated with the use of the Services in this Service and transactions with digital, assets, currencies, and their derivatives.</p>
<p>If Crypto Soul takes the unilateral decision that you have violated these Terms, that the provision of the Services of this Service in the territory of your jurisdiction is illegal or your actions while using the Services of this Service are illegal, then we have the right to suspend or terminate your account at any time, suspend or terminate the provision of Services of this Service used by you, or transactions, operations with digital assets. The Services provided by Crypto Soul may be prohibited by law in certain jurisdictions. The usage of Services of this Service is forbidden for individuals in the following prohibited and contentious jurisdictions: Afghanistan, Albania, Algeria, Bangladesh, Bolivia, Burma (Myanmar), Burundi, Central African Republic, Guinea (Conakry), Cuba, North Korea (DPRK), Ghana, Guinea Bissau, Haiti, Iran, Iraq, Lebanon, Libya, Mali, Myanmar, Nicaragua, Pakistan, Qatar, Saudi Arabia, Somalia, South Sudan, Sudan, Syria, Tunisia, Uganda, United States of America (USA), Vanuatu, Venezuela, Yemen, Zimbabwe and Unrecognized territories with international law.</p>
<p>1.	You are made aware of the fact that this Service is only a place for you to obtain information about digital assets, search for trading partners, conduct negotiations and transactions, operations with digital assets; this Service is not involved in any of your transactions, therefore, you must independently and carefully determine the authenticity, legitimacy, and validity of the respective digital assets and / or information, and independently bear the liability and loss arising therefrom.</p>
<p>2.	The content of these Terms may change at any time without prior notice to users. By using this Service, you agree to constantly review and monitor the update times, changes and amended content of these Terms; if you do not agree with the corresponding changes, you should immediately stop using the Crypto Soul Services; your continued use of the Crypto Soul Services will mean that you accept and agree to the updated Terms.
<p>3.	There are also risks associated with the use of the Internet-based transaction system, including but not limited to software, hardware, and Internet connection failures. Since we have no control over the reliability and availability of the Internet, we are not responsible for distortions, delays, and connection failures.</p>
<p>4.	Crypto Soul under these Terms is not your agent, trustee or representative.
Section  I. Terms and definitions.</p>
<p>•	Crypto Soul is an online platform consisting of a set of online products (services) (P2P platform (web / bot / mobile application), Crypto Soul Exchange, P2P lending, Cryptocurrency gateway), including a website, mobile application and other forms of applications, for the provision of Services set, intended for the users to carry out operations/deals, transactions of digital assets, owned by the legal entity Crypto Soul limited, which is registered under the laws of Hong Kong, located at UNIT 617, 6 / F, 131-132 CONNAUGHT ROAD WEST, SOLO WORKSHOPS, HONG KONG, including but not limited to employees, officers, directors and shareholders, affiliates, contractors, consultants and others.</p>
<p>•	Crypto Soul Services refer to the various online products (services) provided to you by Crypto Soul (P2P platform (web / bot / mobile application), Crypto Soul Exchange, P2P lending, Cryptocurrency gateway), which are based on internet and / or blockchain technologies and are offered through Crypto Soul, mobile applications, customers and through any other forms that already exist, or which will exist.</p>
<p>•	Crypto Soul p2p (or “web p2p exchange”, or “bots” or “Crypto Soul” or “Service”) is an advertising board for digital assets traders with wallet and escrow service and other accompanying services for p2p exchange.</p>
<p>•	Crypto Soul p2p lending — an online lending platform with the means of digital assets, where lenders and borrowers are individuals registered as Crypto Soul users, and this service acts as an intermediary, a connecting point between the lender and the borrower, it determines the rules for using the service and monitors their implementation.</p>
<p>•	User — individuals, institutions or organizations that register in this Service or act without registration but use this Service and all its components and functions, in accordance with the Terms and other Regulatory instruments presented in the Service.</p>
<p>•	Digital currencies (hereinafter referred to as “cryptocurrency”, “digital currency”) refer to encrypted or digital tokens or digital currencies with a specific value that are based on blockchain technology and cryptography, record for internal accounting units of which is provided by a decentralized system (there is no internal or external administrator or any equivalent), working in a fully automatic mode.</p>
<p>•	Digital assets — are digital currencies, their derivatives, or other types of assets with a certain value, circulating in a decentralized system by means of blockchain technology and cryptography.</p>
<p>•	Escrow — the process of arranged storage of digital assets by the Service to ensure and guarantee the execution of the transaction between registered users when using the Crypto Soul p2p advertising board for the purchase and exchange of digital assets, as well as when using the Crypto Soul p2p lending service.</p>
<p>•	Exchange— organizer of trading for digital assets, their derivatives and other market instruments. Trading is conducted via standard contracts or orders, the size of which is determined by the Regulatory instruments of the exchange.</p>
<p>•	Account — functional part of Crypto Soul, intended for accounting of user’ funds, which includes a personal profile, personal profile data provided by the user.</p>
<p>•	Exchange rate — the cost of one digital currency for the purpose of converting it into another.</p>
<p>•	Fees — any remuneration, fees and/or commissions, paid by the users in favour of Crypto Soul, which are established by Crypto Soul separately for each product and are regularly published at: https://Crypto Soul.com/en/fees or in a separate document for each individual product.</p>
<p>•	Personal profile — functional part of Crypto Soul online products, intended for accounting of users’ funds, transactions records, including personal data provided by the user during registration.</p>
<p>Section II. General Provisions</p>
<p>2.1. These Terms consist of the text itself, Regulatory instruments (https://Crypto Soul.com/terms-of-service-Crypto Soul/) and Privacy Policy (https://Crypto Soul.com/cookies-2/), as well as various rules, statements, clarifications, already published or those that will be published in the future.</p>
<p>2.2. Before using any of the Services provided by Crypto Soul, you should read these Terms carefully, and in the event of incomprehension of any parts of the Terms or in other necessity, consult a professional lawyer. If you do not agree with these Terms and / or changes to it at any time, we ask you to immediately stop using the Services provided by Crypto Soul and no longer enter/login into this Service. Login to the Service, use of any Services provided by Crypto Soul, or any other similar actions are considered as a sign that you have understood and fully accepted the content of each clause of these Terms, including any changes to these Terms at any time.</p>
<p>2.3. After registering, filling out the relevant information in accordance with the requirements of this Service and passing other procedures, you become a User of this Service; by clicking the “Completely agree” button during the registration process, you express your absolute agreement with Crypto Soul and its Terms; or if you, while using this Service, press any buttons with inscriptions indicating the meaning of consent or use the Services provided by this Service without consent, it will mean that you fully understand, agree and accept the limitations of all provisions of these Terms;</p>
<p>2.4. By acquiring user status, you become the owner of a user personal profile with a password that you invented yourself; it is the user’s responsibility to keep this personal profile and password safe; the user is legally responsible for all activities and events carried out with the help of his personal profile.</p>
<p>2.5. By registering and using this Service and any other Services provided by Crypto Soul, you represent and warrant that:</p>
<p>– Confirm that you have reached the age of 18 or other legal age in the jurisdiction in which you carry out your activity, legal age giving you the right to conclude contracts in accordance with various applicable laws,  whether it is a registration, sale or purchase, publication of information in this Service and other actions to accept the Services of this Service, these actions must comply with the relevant laws and regulatory instruments of a sovereign state or territory of jurisdiction of your registration and / or residence. In addition, you should have sufficient legal capacity to accept these Terms, conclude contracts, execute contracts, make transactions with digital assets through this Service.</p>
<p>– The digital assets you use are legally obtained and are in your possession in a legal way;</p>
<p>– Agree to take full responsibility for any profits or losses caused by your actions to carry out or not to carry out transactions, deals;</p>
<p>– Confirm that the information provided by you during registration with Crypto Soul is truthful and accurate;</p>
<p>– You agree to follow and comply with any applicable laws, as well as in relation to the tax service, including the declaration of profits from any transactions, deals and operations with digital assets and their derivatives;</p>
<p>– Without limitation, you agree not to send, create or respond to so-called email-bombs (i.e. send by email or send copies of a single message to multiple users, or send large or multiple files or messages to a single user with malicious intent) or send spam (i.e. send unsolicited emails or messages for business or other purposes) or take any other action that may adversely affect the performance or use of the Service by any other person/individual. You may not reproduce, sell, resell or otherwise use any resource or access to any resource contained in this Service;</p>
<p>–  You undertake not to engage in activities or take part in actions that violate the interests of the Service and Crypto Soul as a whole, regardless of whether these activities and actions are related to the Amenity (Service) you use in this Service;</p>
<p>– Crypto Soul and changeBot and all materials used by CRYPTO SOUL LIMITED are protected by copyright and/or other intellectual property rights.</p><p> All logos or images included in this Service are also subject to intellectual property protection.</p>
<p>Section III. Registration Data</p>
<p>3.1. Requirements for registration</p>
<p>You represent and warrant that during the registration procedure or when actually using the Services, you should be an individual, legal entity or other organization, with the necessary competence and rights under applicable law for the purpose of signing these Terms in order to use the Services of this Service. You agree to provide complete and accurate information upon the opening of your Crypto Soul personal profile and agree to promptly update any information, which you provide to Crypto Soul to maintain the integrity and accuracy of the information. If your personal profile is suspected of fraudulent or any other criminal activity, as well as for violation of these Terms, Crypto Soul reserves the right to cancel or freeze your account and hold you or your authorized representative liable under the law.</p>
<p>3.2. Registration (sign-up) Process.</p>
<p>3.2.1. Your registration of a personal profile with Crypto Soul will be considered as your consent to provide necessary personal information for identity verification. Such information will be used to verify the identity of the Users, detect traces of money laundering, terrorist financing, fraud, and other financial crimes made through Crypto Soul or for other legitimate purposes. If required, in accordance with the provisions of the relevant laws and regulatory instruments of the various areas of the law, if requested by Crypto Soul staff, you should provide your real name, original ID and other information, established by laws and regulations, confidentiality and anti-money laundering regulations, and continually update registration materials so that they meet the requirements of timeliness, detail and accuracy. All initially entered information is used as registration materials.</p>
<p>3.2.2. You should be responsible for the authenticity, completeness and accuracy of such information and bear any direct and indirect loss or adverse consequences incurred arising therefrom. If the Crypto Soul administration has any reason (directly or through third parties) to believe, that any information provided by you is incorrect, false, outdated, or incomplete or you refuse to change your personal information, and / or the Crypto Soul administration cannot contact you using the contact information you provided, then your personal profile, or everything related to it, is canceled, or becomes temporarily suspended. In this regard, you undertake the following after registering your personal profile:</p>
<p>—  to update all the information about yourself, if there are any changes to inform about such changes via email: management@Crypto Soul.com;</p>
<p>— to authorize investigation that Crypto Soul deems necessary, directly or through a third party, to verify your identity or protect you, other users;</p>
<p>— to accept sole responsibility for the security of your personal profile and password, responsibility for all transactions, deals within your personal profile.</p>
<p>Crypto Soul is not responsible for any losses or consequences caused by authorized or unauthorized use of your personal profile data, including but not limited to disclosing information, releasing information, agreeing, or submitting various rules and terms by clicking on the website, renewing the terms and any other actions.</p>
<p>3.2.3. The information we need to verify your identity may include, but is not limited to, your name, email address, contact information, phone number, username, government issued ID, date of birth, and other information collected during personal profile registration.</p>
<p>3.2.4. You agree to receive emails and / or text messages sent by this Service related to the management and operation of this Service.</p>
<p>3.2.5. Crypto Soul may from time to time hold contests with other platforms and therefore has the right to ask users for their contact information. Any information you provide will be kept absolutely confidential and will only be used in connection with contests.</p>
<p>3.2.6. Your personal data will be properly protected and kept confidential, but Crypto Soul has the right to collect, process, use or disclose your personal data in accordance with the Terms (including the Privacy Policy) or applicable laws. Depending on the products, Services, relevant requests, your personal data may be transferred to the following third parties: Crypto Soul administration, shareholders, partners, investors, directors, executives, senior managers and employees of such organizations, subsidiaries, business partners, contractors, suppliers, third party service providers and professional consultants, including parties that have been contracted to provide us with administrative, financial, investigation, operational, IT and other services in areas such as telecommunications, information technology, payroll, information processing, training, market research, storage and archiving, third-party business partners, regardless of whether they cooperate with us or not, professional advisers such as auditors and lawyers, relevant government regulators or law enforcement authorities in order to comply with the law or regulations formulated by government agencies, legal successors of our rights and duties, persons/individuals with your consent as determined by you or the applicable Terms.</p>
<p>Section IV. Services</p>
<p>4.1. After registration of a personal profile, the user can:</p>
<p>— view on this Service in real time digital assets and information about transactions, deals;</p>
<p>— have the right to use the functions provided by this Service to carry out transactions;</p>
<p>— create advertisements for deals, digital asset transactions and become an advertiser (“advertising”, or “ads”, or “advertisements”, or “commercial”) for the purpose of selling or acquiring digital assets using the presented Crypto Soul products;</p>
<p>— initiate deals (“trading”, or “contacts”, or “transactions”, or “deals”), by contacting advertisements created by other users, or waiting for other users to start trading with you by contacting advertisements created by you. By initiating a deal, you agree to be bound by trading terms set forth by the advertiser. Trading terms are displayed and set by users on the page with ads.</p>
<p>4.2. The trading terms specified by the advertiser are valid in all cases, unless the terms of the advertiser contradict the Crypto Soul Terms, or are illegal, or if both parties to the deal agree to change the trading terms. The terms of the deal which the user (advertiser) writes in his advertisement, are of recommendatory nature and cannot serve as a compelling argument in a dispute.</p>
<p>4.3. The price or price equation defined in the ad should contain all the commissions the advertiser requires from the user initiating the trading. After the start of trading, the price of the digital assets specified in the deal is blocked and cannot be changed, additional commissions are excluded. Users may conclude an agreement on additional commissions at their own risk. This cannot serve as a compelling argument in a disputе.</p>
<p>4.4. User advertisements should be placed in the correct payment category, if the category does not exist for the payment method, it should be placed in a different category.</p>
<p>4.5. We may hide, remove, or restrict your ads if you violate these Terms or any other agreement you enter into with Crypto Soul, or otherwise, as specified in these Terms or any other agreement you have entered into with Crypto Soul. We may also use proprietary software for fraud detection, risk modeling, associated with your personal profile. When a user purchases digital assets using traditional electronic payment methods using an escrow service, the buyer should transfer the exact amount of fiat currency specified in the exchange transaction, in one payment and using the payment method with the help of which the transaction is carried out. Organization of sending of a multiple payment — at your own risk. This cannot serve as a compelling argument in a dispute.</p>
<p>4.6. In the event of a violation of these terms, sellers are not required to release digital assets without the request of the Crypto Soul support staff, and the deal, the transaction may be canceled at the discretion of the support staff.</p>
<p>4.7. Users should be prepared to verify their identity and present proof of payment for Crypto Soul, otherwise the deal, the transaction may be canceled at the discretion of the Crypto Soul staff.</p>
<p>4.8. Users should independently verify the identity of the counterparty and the legitimacy of fiat money, as far as possible at any stage before the transaction. Crypto Soul cannot verify the legitimacy of the sources of fiat money or digital assets and is not responsible in any way for your activities. By accepting these Terms, you confirm that you will only buy digital assets with funds obtained from a legal source for your jurisdiction, and you will only sell digital assets obtained from a legal source for your jurisdiction. If you induce Crypto Soul users to work without an escrow or force them to release their digital assets without the seller receiving fiat money, your personal profile will be closed at the discretion of Crypto Soul employees.</p>
<p>4.9. All materials and images in the Crypto Soul service are protected by copyright. Modifying or using the material or any other content for any purpose not permitted by these Terms may be an infringement of copyright and is prohibited. You can view and display the materials and all other content presented on Crypto Soul for non-commercial, personal, entertainment purposes. The materials and all other content on Crypto Soul may not be copied, reproduced, republished, uploaded, published, transmitted, distributed, or used in any way, unless specifically authorized by Crypto Soul.</p>
<p>4.10. The escrow service fee is 0.5% of Seller’ or Buyer’ deal/ transaction amount after the transaction is completed.</p>
<p>4.11. Transactions are sent to the network with a timeout. The real network commission and the time until the first confirmation depends on the current network status and wallet settings for digital assets, which we set at our discretion.</p>
<p>4.12. Commission and wallet information is available at https://Crypto Soul.com/wallets_stat/; In addition, we can carry out your withdrawal absolutely free of charge if you use a free withdrawal voucher.</p>
<p>4.13. The digital assets involved in the transaction are held in escrow throughout the entire trading process until the seller receives payment in full. Buyers of digital assets must be able, upon Crypto Soul request, to provide adequate proof of payment within 180 days of the completion of the transaction. If we find out that your personal profile poses a high risk to Crypto Soul or our customers, we will consider that you have violated these Terms and may temporarily restrict your personal profile and freeze your digital asset wallet in accordance with these Terms. In case of fraudulent attempts using the specifics of the Telegram application (no streaming messages) with a change in the rate in advertising by a significant % right before the start of the deal — we can block user personal profile for 90 days with all balance. Significant % — rate change by — / + 10 % of the previously specified rate.</p>
<p>4.14. If the buyer and seller of a digital asset deal disagree about the deal, either the party or Crypto Soul can initiate a dispute. Controversial deals are resolved by Crypto Soul Arbitrator. Crypto Soul Arbitrator resolves disputes by carefully assessing whether the deal, the transaction violates these Terms, examines proof of payment, trade chat messages, user reputation, other data provided to us by our users, and data collected by us as part of our Privacy Policy.</p>
<p>4.15. In case the sellers stop responding, we will resolve the dispute with the buyer if we are confident that the seller received a valid payment from the buyer. If the buyer does not respond, the seller can dispute the deal and we will resolve the dispute for the seller. Once the deal has been authorized by the seller, the transaction is considered complete and cannot be challenged, canceled, or changed by users. Completed deals can only be challenged by Crypto Soul in the event that the deal was unduly completed. While we are considering a dispute on a completed deal, we charge an additional fee of 10% of the transaction amount due to user error and violation of the Terms. Other disputes are at no commission of 10%.</p>
<p>4.16. Providing false information or documents in a dispute, false statements, attempts to influence with their actions or documents on a certain outcome of the disputed trading is considered a violation of this agreement. Disputes over “Cash” transactions and other payment methods during personal meetings are not allowed for disputes. If payment details are provided outside of Crypto Soul, the dispute may be resolved without considering the payment details. In case the buyer sent the required amount, but violated the seller’s terms, the seller is obliged to either refuse the fiat payment (refund) or accept such payment, thereby completing the transaction, or if the buyer has sent part of the required amount. At the time of processing the refund, the transaction is in the status of a dispute until the actual refund of fiat funds.</p>
<p>4.17. If you invite a new user through your personal link, and he is settled as your “referral”, you will receive dividends from his exchange activity. You get 0.12% of the transaction amount if your referral makes a transaction by responding to an advertisement, and 0.08% of the transaction amount if your referral created an ad that was responded to by another user. Crypto Soul does not pay dividends for wallet fees.</p>
<p>4.18. Cancellation / correction of a transaction: before the transaction is completed, you have the right to cancel or amend the order at any time.</p>
</p>Section IV. Posts, messages, publications, and emails</p>
<p>5.1. In accordance with these Terms, we do not accept or consider unsolicited information from you or any other content. Therefore, please do not submit any unsolicited materials to Crypto Soul.</p>
<p>5.2. Crypto Soul has the right to request information from you with regard to your deals, transactions, personal information, and any other, that does not contradict these Terms and the laws of the jurisdiction in which your personal profile is registered.</p>
<p>5.3. You can use Crypto Soul and its contents only for legitimate purposes and in accordance with applicable law, and you are prohibited from storing, distributing, or transmitting any illegal material through Crypto Soul. You acknowledge that the storage, distribution, or transmission of illegal materials may result in criminal and / or civil liability or any other liability.</p>
<p>5.4. You agree that if a third party claims that the material you have posted on the Crypto Soul service is illegal, you yourself bear the burden of proving its legality. You understand and agree that all materials published in the public domain (except Crypto Soul) or privately transferred to Crypto Soul or through Crypto Soul are the sole responsibility of the sender, not the Crypto Soul, and that you yourself are responsible for all material that you upload, post, or otherwise transmit through Crypto Soul.</p>
<p>5.5. You can not:</p>
<p>5.5.1. Publish in / through Crypto Soul defamation, invasion of privacy, harassment, publish pornography, racism, insults, threats;</p>
<p>5.5.2. Disseminate and use information that seeks to exploit or harm children, display inappropriate content, request personal information;</p>
<p>5.5.3. Violate any intellectual property or other rights of any legal entity or individual, including infringement of anyone’s copyright or trademarks or their publicity rights;</p>
<p>5.5.4. Violate any law or anything that could be considered a violation of the law;</p>
<p>5.5.5. Publish, use, distribute information under any contractual or other relationship (for example, inside information, official/corporate or confidential information obtained in the context of an employment contract or nondisclosure agreement);</p>
<p>5.5.6. Promote or inflict on illegal activities;</p>
<p>5.5.7. Forge headlines, impersonate another person, or otherwise manipulate identification, to hide your identity or the source of any messages or transmissions you send to Crypto Soul;</p>
<p>5.5.8. Advertise any commercial activity (e.g. sell products or services) or otherwise engage in any commercial activity (for example, run giveaways and contests, display sponsored banners and / or solicit goods or services), except as specifically permitted by Crypto Soul and only with written consent;</p>
<p>5.5.9. Raise funds, find advertisers or sponsors;</p>
<p>5.5.10. Enable programs containing viruses, computer worms and / or Trojan horses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software, equipment or telecommunications, investigate, scan or test Crypto Soul vulnerabilities, violate any security or authentication measures, Crypto Soul verification, or any network connected to Crypto Soul;</p>
<p>5.5.11. Disrupt the normal flow of dialogue, make the screen scroll faster than other users can type, or act in a way that affects the normal working ability of other people to participate in real-time action with Crypto Soul;</p>
<p>5.5.12. Copy any other pages or images of Crypto Soul;</p>
<p>5.5.13. Use any external links, web crawlers, bots, spiders or other automated devices, programs, scripts, algorithms or methods, any similar or equivalent manual processes for accessing, obtaining, copying or monitoring any part of the Services, databases, Crypto Soul technologies, to receive or attempt to obtain any materials, documents or information in any way that was not intentionally provided through Crypto Soul;</p>
<p>5.5.14. Attract money or digital assets from other users using a “Ponzi scheme” or a similar scheme;</p>
<p>5.5.15.  Raise funds or digital assets for a “data warehouse” (i.e. using any web space available to you as storage for large files that are only linked from other sites). You should provide a reasonable amount of content to accompany such materials so that at least some of the traffic to your site goes directly through Crypto Soul;</p>
<p>5.5.16. Disobey any policy or rules established from time to time regarding the use of Crypto Soul or any networks connected to Crypto Soul;
<p>5.5.17. Remove any sponsored banners or other materials posted by Crypto Soul anywhere (for example, on any web space available for your use).
<p>1.	Restrictions</p>
<p>6.1. You understand and agree that under any circumstances Crypto Soul, its affiliates and their executive body, officials, employees, lawyers, agents, representatives, and any other individuals and legal entities involved in the activities of Crypto Soul individually and collectively assume no liability or responsibility for the following events: loss of income, digital assets and / or funds, loss of profit from deals, transactions or contractual losses, interruption in operations, foreseeable monetary damage, loss of information, loss of opportunity, damage to commercial reputation or notoriety, damage or loss of data, cost of purchased replacement of products or services, any consequential, special or incidental loss and damage caused by infringement of rights (including errors), violation of agreements or any other reason, regardless of whether we could reasonably have foreseen this loss or damage, regardless of whether we were informed in advance of the possibility of such loss or damage, any consequential damages.</p>
<p>6.2. You understand and agree that under any circumstances Crypto Soul, its affiliates and their executive body, officials, employees, lawyers, agents, representatives, and any other individuals and legal entities involved in the activities of Crypto Soul individually and collectively assume no liability or responsibility for the compensation for any of your damage caused by any of the following circumstances: Crypto Soul has reasonable grounds to believe, that in your specific deals, transactions there are violations of the law, morality, violation of these Terms, misunderstanding by you of the Services provided by Crypto Soul, any other losses related to the Services provided by Crypto Soul, which occurred through no fault of ours.</p>
<p>6.3. Crypto Soul, its affiliates and their executive body, officials, employees, lawyers, agents, representatives, and any other individuals and legal entities involved in the activities of Crypto Soul individually and collectively assume no liability or responsibility for the inability to provide Services or delay in the provision of Services, as well as the resulting losses caused by the maintenance of information network equipment, failure of the information network connection, failure of a computer, communication or other systems, power failure, natural causes, unexpected accidents, strikes, labor conflicts, riots, uprisings, unrest, lack of productivity or means of production, fire, flood, hurricane, explosion, war, pandemic, quarantine, the fault of banks or other partners, the collapse of the digital asset market, government actions, orders of judicial or administrative authorities, as well as other actions or activities of third parties outside and beyond of our control.</p>
<p>6.4. Crypto Soul, its affiliates and their executive body, officials, employees, lawyers, agents, representatives, and any other individuals and legal entities involved in the activities of Crypto Soul individually and collectively cannot guarantee that all information, programs, documents, etc. contained in online products are completely safe, not subject to tampering or damage as a result of any viruses, Trojan horses or other malicious software; logging into the system, using any Services and downloading any programs, information, data from this Service is your personal decision and you yourself bear the risks and possible losses arising therefrom; if you use any services, information and products provided by services or websites of third parties, then it is your personal decision and you yourself bear all the responsibility arising therefrom; in addition, Crypto Soul does not provide any express or implied guarantees, regarding your use of the Crypto Soul Services, including, but not limited to, applicability, absence of errors and omissions, continuity, accuracy, reliability, suitability for a particular purpose. Furthermore, we also do not make any promises or guarantees about performance, accuracy, appropriateness, reliability, quality, stability, completeness or timeliness of technologies and information that Crypto Soul Services relate to. You make a personal decision about whether to use Crypto Soul Services and independently bear the risks and possible losses arising thereof. We do not provide any express or implied guarantees about the market, value, and price of digital assets; you are made aware and understand that the digital asset market is unstable, value and prices are subject to significant fluctuations or collapse at any time; execution of deals, transactions with digital assets is your personal free choice and decision, you yourself bear all the responsibility or possible losses arising therefrom.</p>
<p>6.5. Your registration or use of Crypto Soul Services without registration is considered as a sign of your acknowledgment of the fact, that you bear any risks arising from any activity conducted by us in accordance with the rules set forth in these Terms. Compared to fiat money, there may be more significant fluctuations in the price of digital assets, used to determine the value of a user’s position. There is a high probability that the User will not receive a fair and accurate price for the base digital currency when trading.
The user should only participate in deals and transactions if he has a complete understanding of the financial markets and fully understands the risks associated with cryptocurrencies.</p>
The User understands that Crypto Soul does not in any way affect the rate set by the Users, does not give any recommendations regarding the determination of the rate, and does not make predictions about the rates. The User is responsible for all economic risks associated with the choice of a particular rate. Crypto Soul does not guarantee that the deal, the transaction will be completed and that its conditions will be beneficial for the User.</p>
<p>6.6. You agree to indemnify for any damages, fines or penalties imposed by any regulatory body arising out of your use of Crypto Soul’s Services, your violation of any applicable law, regulation or third party rights when you use the Crypto Soul Services. If you are obligated to reimburse your liability to Crypto Soul operators, their affiliates, contractors, licensors and their respective directors, officers, employees, or agents in accordance with these Terms, Crypto Soul will have the right, in its sole discretion, to monitor any actions or procedures and determine whether Crypto Soul wishes to make the settlement, and if so, on what terms.
<p>VII. Personal profile and account</p>
<p>7.1. Information about the personal profile, account, deals, transactions is stored in accordance with the law for 5 calendar years.</p>
<p>7.2.  Crypto Soul regularly sets and adjusts the maximum daily limit of deals, transactions, and currency directions for each personal profile and account as well as for all users in general. In the event that the number of your deals, transactions on your personal profile and account has exceeded the allowed limits, Crypto Soul has the right to recognize your deals, transactions as suspicious through its own decision and, without notifying you, has the right to suspend such deals, as well as refuse the requested and subsequent deals, transactions, block digital assets to determine their origin in your personal profile and your account. All abovementioned actions Crypto Soul has the right to perform both separately from each other and simultaneously.  In this case, you agree to provide written and duly certified proof, confirming the legitimacy of the existence of your ownership of your digital assets.</p>
<p>7.3. Cancellation of your personal profile and your account may occur upon your written request.  You agree to withdraw all digital assets from your personal profile and account within 10 calendar days from the date of filing and submitting an application for termination (cancellation) of your personal profile and account to Crypto Soul.</p>
<p>7.4. Crypto Soul may block, terminate your personal profile and account if you do not take any actions on the online Service for one calendar year,  directly or indirectly register as a user under someone else’s personal data, during the use of your personal profile or upon registration the Crypto Soul administration reveals the fact that you have provided incomplete, misleading and inaccurate information, if you do not agree with these Terms, and for other reasons where Crypto Soul considers that it has the right to terminate the provision of Services and cancel your personal profile and account.</p>
<p>7.5.  Crypto Soul assume no liability or responsibility (neither material, nor monetary, nor administrative, nor criminal, nor civil and no other) for retention of digital assets for the reasons indicated in these Terms.</p>
<p>7.6. In case of loss or discrediting of the password and / or data of the Personal Profile, as well as in case of illegal access to the personal profile by third parties, the User is obliged to immediately inform the Technical Support Service of Crypto Soul of such events ( https: // support. Crypto Soul.com/en-RU/support/home ). Until Crypto Soul receives such a message, all actions performed using the User’s Personal Profile will be considered as such performed by the User as the owner of the Personal Profile.</p>
<p>7.7. The user confirms and agrees that the deposit and withdrawal of funds may be delayed due to the particularities of the networks. The User acknowledges and agrees that the deposit and withdrawal of digital assets to his Personal profile may take from one (1) hour to seventy two (72) hours, apart from unforeseen or unavoidable network problems.</p>
<p>VIII. Dispute resolution and arbitration</p>
<p>8.1. In case of any disputes, claims or written applications, you agree to notify Crypto Soul in advance in writing.</p>
<p>8.2. Any disputes, claims and written communications to Crypto Soul shall not be made public, published, or discussed orally with third parties not engaged in the dispute. Otherwise, you agree to pay Crypto Soul a penalty for the violation specified in this clause and for any other violation of these Terms in the amount of 20% of the user’s deposit at the time Crypto Soul detects a violation.</p>
<p>8.3. Crypto Soul undertakes to consider and respond at its discretion to any written requests, claims of users within 30 calendar days.
<p>8.4. Crypto Soul undertakes to resolve the dispute between users within 5 calendar days in case of timely provision of information. The period for considering a dispute may be extended at the discretion of the arbitrator.</p>
<p>8.4.1.  The dispute is considered open if the user pressed the “Open dispute” button.</p>
<p>8.4.2. The user undertakes to provide Crypto Soul with all available information regarding the dispute, namely: all available information, documents, access to the user’s Internet bank through the TeamViewer application exclusively for the purpose of tracking bank transactions under the deal and nothing more.</p>
<p>8.4.3. In case the dispute can not be resolved in a satisfactory manner, and you intend to file a legal claim against Crypto Soul, then you agree to state the basis for such a claim in writing in English, where you describe the reason for the claim, grounds, deal number, specific remedy that you are seeking for, email address for feedback, your personal profile name.</p>
<p>8.5. You agree that any arbitration will be conducted in English or Russian at the user’s choice. Place of Arbitration: The place of arbitration is Hong Kong. Place of Hearing: The venue for any personal arbitration hearing will be Hong Kong, unless otherwise agreed by the parties. The parties agree that the arbitration will be confidential. The existence of the arbitration, any non-public information provided during the arbitration, and any representations, orders or decisions made during the arbitration cannot be exposed to any person that is not a party, except for the arbitral tribunal, parties, lawyers of the parties, experts, witnesses, accountants and auditors, insurers, as well as any other person required to conduct arbitration.</p>
<p>8.6.  You agree that any claims, lawsuits related to these Terms or Crypto Soul products shall be brought against the other party in the arbitration on an individual basis only. In accordance with these Terms, you waive class action claims.</p>
<p>1.	I Miscellaneous</p>
<p>•	Crypto Soul receives information requests about its clients from law enforcement agencies around the world.
Typically, law enforcement agencies are interested in two types of data: information about the personal data of our clients and information about the trading activities of our clients.</p>
<p>•	Crypto Soul provides the requested information only on the basis of a formal legal request drawn up in accordance with all requirements of international law or the laws of Hong Kong. Crypto Soul provides only the information specified in the request and in compliance with international law or the laws of Hong Kong.</p>
<p>•	Crypto Soul also reserves the right to disclose information to authorities, law enforcement agencies in order to protect our interests, as well as the interests of our clients.</p>
<p>•	By using online services from Crypto Soul, you agree to the Crypto Soul Terms of Service.
For information on cookies, please visit: https://Crypto Soul.com/cookies
For information on KYC / AML , please visit: https://Crypto Soul.com/kycaml
For information on the official responses, please visit: https://Crypto Soul.com/ official_replies
How to contact us: CRYPTO SOUL LIMITED, Hong Kong. UNIT 617, 6 / F, 131-132 CONNAUGHT ROAD WEST, SOLO WORKSHOPS HONG KONG Hong Kong CR
Registration number: 2717458</p>


<?php 
	include('../footer.html');
?>